### ISSUE TITLE
err

### ISSUE THREAD

**Issue by OleksandrIX** [OleksandrIX/CassandraApp#1]
Traceback (most recent call last):
  File "/home/oleksandr/cassandra-app/CassandraApp/main.py", line 1, in <module>
    from desktop_class import CTkApp
  File "/home/oleksandr/cassandra-app/CassandraApp/desktop_class.py", line 1, in <module>
    import tkinter
ModuleNotFoundError: No module named 'tkinter'

**Comment by OleksandrIX** [comment]
pip install customtkinter 
pip install cassandra-driver

**Comment by OleksandrIX** [comment]
pip install python-tk

**Comment by OleksandrIX** [comment]
curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(pyenv init -)"' >> ~/.bashrc
source ~/.bashrc

**Comment by OleksandrIX** [comment]
pyenv install 3.10.7
pyenv global 3.10.7
python --version
